### PR TITLE
fix `globalThis.process` conflict

### LINKED ISSUE #106: `globalThis.process` references DOM elements with a `#process` ID and crashes app
### Bug description
DOM Elements are referenced as global variables via their unique ID's.
When an element with a `#process` ID exists on the page, it is referenced via `window.process` and via `globalThis.process`, which causes [this function](https://github.com/sindresorhus/emittery/blob/main/index.js#L218-L227) to crash.

### Reproduction
See my reproduction here and follow the comments:
https://stackblitz.com/edit/emittery-process-crash?file=src%2Fmain.ts&terminal=dev

### PR DESCRIPTION
**Pull request by alexiglesias93**
Fixes #106

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -223,7 +223,7 @@ export default class Emittery {
 
 		// eslint-disable-next-line n/prefer-global/process
```
Comment (sindresorhus) [inline index.js:224]: It would be clearer to change `typeof globalThis.process !== 'object'` to `typeof globalThis.process?.env !== 'object'`.

It also needs a code comment to quickly explain why we don't just check `globalThis.process`.

Comment (alexiglesias93) [reply index.js]: Thanks @sindresorhus , addressed in 75bea4b5853c4d82e032bd5048e98f7850316f7b
